### ISSUE TITLE
early_stopping not permitted?

### ISSUE THREAD

**Issue by HURIMOZ** [eole-nlp/eole#114]
Hi, is early_stopping available in Eole NLP? If so, how to use it? And can we choose a criteria for the early_stopping?

I get this error:
```(TY-EN) ubuntu@ip-172-31-2-199:~/TY-EN/eole/recipes/wmt17$ eole train --config wmt17_enty.yaml
Traceback (most recent call last):
  File "/home/ubuntu/TY-EN/TY-EN/bin/eole", line 33, in <module>
    sys.exit(load_entry_point('eole', 'console_scripts', 'eole')())
  File "/home/ubuntu/TY-EN/eole/eole/bin/main.py", line 39, in main
    bin_cls.run(args)
  File "/home/ubuntu/TY-EN/eole/eole/bin/run/train.py", line 68, in run
    config = cls.build_config(args)
  File "/home/ubuntu/TY-EN/eole/eole/bin/run/__init__.py", line 42, in build_config
    config = cls.config_class(**config_dict)
  File "/home/ubuntu/TY-EN/TY-EN/lib/python3.10/site-packages/pydantic/main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for TrainConfig
model.transformer.early_stopping
  Extra inputs are not permitted [type=extra_forbidden, input_value=4, input_type=int]
    For further information visit https://errors.pydantic.dev/2.8/v/extra_forbidden
```

**Comment by HURIMOZ** [comment]
Oh I see mistake. I placed early_stopping in the wrong section of the config file. I ʻve now put it into the training section and it now works.
However, the criteria still wonʻt work. Not sure why.
