### ISSUE TITLE
ValidationError during eole predict: Extra inputs not permitted for PredictConfig

### ISSUE THREAD

**Issue by HURIMOZ** [eole-nlp/eole#170]
Hello guys, Iʻve just updated Eole NLP to the latest version (0.0.3). When trying to run inference using eole predict, I now get a validation error related to the PredictConfig. The error suggests there's an issue with a dummy_load parameter, though this parameter is not explicitly defined in my configuration file:
```
(TY-EN) ubuntu@ip-172-31-3-172:~/TY-EN/LLM$ eole predict -c tower-inference.yaml -src promptized-test.en -output test.ty
Traceback (most recent call last):
  File "/home/ubuntu/TY-EN/TY-EN/bin/eole", line 33, in <module>
    sys.exit(load_entry_point('eole', 'console_scripts', 'eole')())
  File "/home/ubuntu/TY-EN/eole/eole/bin/main.py", line 39, in main
    bin_cls.run(args)
  File "/home/ubuntu/TY-EN/eole/eole/bin/run/predict.py", line 42, in run
    config = cls.build_config(args)
  File "/home/ubuntu/TY-EN/eole/eole/bin/run/__init__.py", line 42, in build_config
    config = cls.config_class(**config_dict)
  File "/home/ubuntu/TY-EN/TY-EN/lib/python3.10/site-packages/pydantic/main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictConfig
dummy_load
  Extra inputs are not permitted [type=extra_forbidden, input_value=True, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.8/v/extra_forbidden
```
Command used:
```eole predict -c tower-inference.yaml -src promptized-test.en -output test.ty```

My config file for inference:
```# Model info
model_path: ["finetune/merged"]

# Inference settings
seed: 42
max_length: 512
batch_type: tokens
batch_size: 512
world_size: 1
gpu_ranks: [0]

# Transforms
transforms: ['huggingface_tokenize']
transforms_configs:
  huggingface_tokenize:
    huggingface_model: "Unbabel/TowerInstruct-7B-v0.2"
    max_length: 512

# Generation settings
compute_dtype: fp16
top_k: 50
top_p: 0.9
beam_size: 6
min_length: 10
temperature: 0.7
n_best: 1
src: None

# Logging
report_time: true
```

**Comment by vince62s** [comment]
yes there has been some patches since 0.0.3
just git pull et if necessary resintall using `pip install -e .`

**Comment by HURIMOZ** [comment]
Hi Vince, I successfully reinstalled eole-0.0.3 with ```pip install -e .``` yet itʻs still throwing the same error.
